### ISSUE TITLE
Add the option to output the report as a pdf

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/rep-cred#24]
Feature requested by @bcorrie

**Comment by ssnn-airr** [comment]
Done in cb3679e826f2fd65de36d352d8060be762e94681

**Comment by bcorrie** [comment]
@ssnn-airr it looks like the docker container doesn't have pdflatex installed so generating PDF fails.

I am building the container with these packages added:

```
    texlive-latex-base \
    texlive-fonts-recommended \
    texlive-fonts-extra \
    texlive-latex-extra \
```
Will let you know if that works...

**Comment by ssnn-airr** [comment]
Added texlive to the container in 303ef76744bdb65d0d1b2b81058233b20eab8b02

**Comment by bcorrie** [comment]
pdflatex is now working in container docker: airrc/rep-cred:latest - thanks.
