### ISSUE TITLE
repcred failure with empty sequence_alignment

### ISSUE THREAD

**Issue by bcorrie** [airr-community/rep-cred#26]
When running on `repertoire_id=5f21e817e1adeb2edc126144` on covid19-1.ireceptor.org, I get:

```
Rendering book in directory '.'

processing file: _main.Rmd
Quitting from lines 389-444 (_main.Rmd) 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'XStringSet': The column sequence_alignment contains no data
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```
Sure enough, this repertoire has this field empty, but it is a nullable field in the standard, so repcred should probably be more robust if this is not available. Not sure which reports this would effect...

**Comment by bcorrie** [comment]
Also occurs on `study_id = IR-Binder-000001, repertoire_id = 5efbc7325f94cb6215deecfc`

**Comment by bcorrie** [comment]
PRJNA381394, subject B00_CLL_05_10x  failed with this error as well... repertoire_id = 12, ipa5.ireceptor.org

**Comment by ssnn-airr** [comment]
I updated the code to skip the part of the code that needs sequence_alignment if there is no sequence_alignment data. I added 5000 sequences of PRJNA381394, subject B00_CLL_05_10x to the tests and seems to work. Can you please update your container and try again?

**Comment by bcorrie** [comment]
Repcred ran fine on the previous problem data sets:

subject_id=B00_CLL_05_10x
repertoire_id=5efbc7325f94cb6215deecfc
repertoire_id=5f21e817e1adeb2edc126144

So it looks like this problem is fixed...

<img width="1022" alt="image" src="https://github.com/airr-community/rep-cred/assets/1105216/ef3a81c4-9b4f-4888-97fb-cacbd250b1f7">
<img width="1025" alt="image" src="https://github.com/airr-community/rep-cred/assets/1105216/83e26bbe-ceaf-403e-9480-5469c0b3d24b">
<img width="1016" alt="image" src="https://github.com/airr-community/rep-cred/assets/1105216/a8b5eb54-8e2d-4cc8-ac4a-a02e5dfe8238">
