### ISSUE TITLE
repcred error on gene call frequency?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/rep-cred#28]
PRJCA002413, `repertoire_id = PRJCA002413-Healthy_Control_3-IGH` on covid19-1.ireceptor.org

```
Rendering book in directory '.'


processing file: _main.Rmd
Quitting from lines 588-624 (_main.Rmd) 
Error in names(freq_table) <- c("sequence", "call", "Freq") : 
  'names' attribute [3] must be the same length as the vector [2]
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

**Comment by bcorrie** [comment]
This repcred analysis now works:

PRJCA002413, repertoire_id = PRJCA002413-Healthy_Control_3-IGH on covid19-1.ireceptor.org


<img width="1030" alt="image" src="https://github.com/airr-community/rep-cred/assets/1105216/c60f441a-a723-4a6d-aedd-49076003f7d8">

**Comment by ssnn-airr** [comment]
Reopen if needed
