### ISSUE TITLE
Generate mark down error

### ISSUE THREAD

**Issue by bcorrie** [airr-community/rep-cred#36]
I get the following on some repertoires - See #35 for details on which repertoires.

processing file: _main.Rmd

Quitting from lines at lines 293-303 [unnamed-chunk-9] (_main.Rmd)
Error in `wrap_dims()`:
! Need 5 panels, but together `nrow` and `ncol` only provide 3.
ℹ Please increase `ncol` and/or `nrow`.
Backtrace:
1. base::local(...)
8. bookdown (local) ``(...)
9. bookdown:::render_cur_session(...)
10. rmarkdown::render(main, output_format, ..., clean = clean, envir = envir)
11. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
...
38. layout$setup(data, plot$data, plot$plot_env)
39. ggplot2 (local) setup(..., self = self)
40. self$facet$compute_layout(data, self$facet_params)
41. ggplot2 (local) compute_layout(..., self = self)
42. ggplot2::wrap_dims(n, params$nrow, params$ncol)
Execution halted

**Comment by ssnn-airr** [comment]
@bcorrie this issued should be fixed now. Please try again.

**Comment by bcorrie** [comment]
For the record, these are the repertoires this failed on:

100 sequences, Sample ID: 1434_exp_RLQ_pos, Failed
10,000 sequences, Sample ID: p1437_CD8ifny Failed

Both of these now work so I think this issue can be marked done.
