### ISSUE TITLE
change R package installation method in the container

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/rep-cred#43]
Failed installations with Rscript result in a warning, not an error, and the build continues even the installation of dependencies failed. Maybe try the [`install2.r`](https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/bin/install2.r) script that comes with `rocker`. And update tests to verify the installation was successful.

**Comment by ssnn-airr** [comment]
I decided to simply add `require` (e9bd37d7394b553b0ae276a8ff2829b56764afed) to check that the packages are installed.

**Comment by ssnn-airr** [comment]
Reviewing the docs, require throws just a warning, so it won't stop the build process. I will change to library.

**Comment by williamdlees** [comment]
Ah, that’s what it was.

 

Shall I change the github and docker names? As I recall the old github name will continue to work, if people have a repo checked out

 

William
