### ISSUE TITLE
set up Travis CI

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/rep-cred#6]
Use the airr-standards `.travis.yml` file as an example.

**Comment by ssnn-airr** [comment]
@schristley can you enable travis for the rep-cred repo? I have 'insufficient permissions'. Thanks!

**Comment by schristley** [comment]
Ok, enabled, I triggered a build for the master branch

**Comment by ssnn-airr** [comment]
And you added a badge! :) Thanks!
