### ISSUE TITLE
Error when re-running an analysis

### ISSUE THREAD

**Issue by williamdlees** [airr-community/rep-cred#9]
Once you have run one analysis in repcred, attempting to run a second analysis results in the message 'Warning: Error in setwd: cannot change working directory'.

**Comment by GeorginaLeslie** [comment]
This looks to actually be fixed already. If the issue is still occurring I will take another look.

**Comment by ssnn-airr** [comment]
I should have closed this when I fixed it. I think the issue was the use of setwd() (commit ddb970a)
